version: '3.0'
services:
  web:
    image: alexcheng/magento2
    ports:
      - "8084:80"
    links:
      - db
    volumes: 
      - magento-data:/var/www/html
    env_file:
      - env
  db:
    image: mysql:5.7.28
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db     
volumes:
  magento-data:
  db-data: 